test_service_public_port: 9000

test_internal_kubernetes_value: "this is PROD - loaded dynamically"

persistent_volume_path: "/run/desktop/mnt/host/c/Projekte/docker/repository/docker-test/de.tecsi.docker.test/kubernetes/prod-mount"