kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: docker-test-role
rules:
  - apiGroups: [""]
    resources: ["configmaps","pods"]
    verbs: ["get","list","watch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: docker-test-role-binding
roleRef:
  kind: Role
  name: docker-test-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: docker-test-account
