kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}-cluster-role
rules:
  - apiGroups: [""]
    resources: ["configmaps","pods"]
    verbs: ["get","list","watch"]


---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Namespace }}-cluster-role-binding
  labels:
    dummy: test
subjects:
- kind: ServiceAccount
  name: docker-test-account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name:  {{ .Release.Namespace }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
