apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-service
spec:
  hosts:
  - msgn19818.hyperv.net
  ports:
  - number: {{ .Values.test_external_port }}
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL