apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-service-entry
spec:
  hosts:
  - {{ .Values.test_external_host }}
  ports:
  - number: {{ .Values.test_external_port }}
    name: http
    protocol: HTTP
  resolution: DNS
  location: MESH_EXTERNAL