kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-internal
spec:
  selector:
    matchLabels:
      app: test-internal
  replicas: 1
  template:
    metadata:
      labels:
        app: test-internal
    spec:
      serviceAccountName: docker-test-account
      containers:
      - name: internal
        image: docker.io/jeskesigi/docker-test-internal:latest
        imagePullPolicy: Always
        env:
        - name: JAVA_OPTS
          value: {{ .Values.test_internal_java_opts }}
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        ports:
        - containerPort: 8081
        volumeMounts:
        - mountPath: /config
          name: test-mount
          subPath: config
        - mountPath: /logs
          name: test-mount
          subPath: logs
      volumes:
      - name: test-mount
        persistentVolumeClaim:
          claimName: test-mount-claim
