kind: ConfigMap
apiVersion: v1
metadata:
  name: test-internal-config
data:
  application.yaml: |
{{- $path := printf "%s/%s" .Values.env "docker-test-internal.yaml" }}
{{ tpl ($.Files.Get $path) $ | indent 4 }}
