kind: Service
apiVersion: v1
metadata:
  name: test-internal
  labels:
    run: test-internal
spec:
  type: NodePort
  ports:
  - name: internal-port
    port: 8081
    protocol: TCP
  selector:
    app: test-internal
