kind: Service
apiVersion: v1
metadata:
  name: test-internal
  labels:
    run: test-internal
spec:
  type: ClusterIP
  ports:
  - name: http-internal-port
    port: {{ .Values.test_internal_port }}
    protocol: TCP
  selector:
    app: test-internal
