kind: Service
apiVersion: v1
metadata:
  name: test-internal
  labels:
    run: test-internal
spec:
  type: LoadBalancer
  ports:
  - name: internal-port
    port: 8081
    targetPort: 8081
    nodePort: {{ .Values.test_internal_public_port }}
    protocol: TCP
  selector:
    app: test-internal
