kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: docker.io/library/mysql:5.7.44
        ports:
        - containerPort: {{ .Values.mysql_port }}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: test-mount
          subPath: mysql-data
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
      volumes:
      - name: test-mount
        persistentVolumeClaim:
          claimName: test-mount-claim
