kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: test-service-route
spec:
  parentRefs:
  - name: test-service-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: test-service
      port: {{ .Values.test_service_port }}