kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: test-service-gateway
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    hostname: "localhost"
    port: 8000
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same