kind: Service
apiVersion: v1
metadata:
  name: test-service
  labels:
    run: test-service
spec:
  type: ClusterIP
  ports:
  - name: http-service-port
    port: {{ .Values.test_service_port }}
    targetPort: {{ .Values.test_service_port }}
    protocol: TCP
  selector:
    app: test-service
