kind: Service
apiVersion: v1
metadata:
  name: test-service
  labels:
    run: test-service
spec:
  type: NodePort
  ports:
  - name: service-port
    port: 8080
    targetPort: 8080
    nodePort: {{ .Values.test_service_public_port }}
    protocol: TCP
  selector:
    app: test-service
