kind: ConfigMap
apiVersion: v1
metadata:
  name: test-service-config
data:
  application.properties: |
    docker-test-service.db.url=jdbc:mysql://mysql:3306/docker-test-service?serverTimezone=UTC
    docker-test-service.db.default_schema=docker-test-service
    docker-test-service.db.username=${MYSQL_USERNAME}
    docker-test-service.db.password=${MYSQL_PASSWORD}
    docker-test-service.internal-api.endpoint=http://test-internal:8081
    docker-test-service.external-api.endpoint=http://test-external:8082
