kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-service
spec:
  selector:
    matchLabels:
      app: test-service
  replicas: 1
  template:
    metadata:
      labels:
        app: test-service
    spec:
      initContainers:
        - name: check-mysql
          image: busybox
          command: ['sh', '-c', "until nslookup mysql; do echo waiting; sleep 2; done"] 
      containers:
      - name: service
        image: docker.io/jeskesigi/docker-test-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 50505
        env:
        - name: JAVA_OPTS
          value: -agentlib:jdwp=transport=dt_socket,address=*:50505,server=y,suspend=n
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        volumeMounts:
        - mountPath: /config
          name: test-mount
          subPath: config
        - mountPath: /logs
          name: test-mount
          subPath: logs
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 1
          httpGet:
            path: /actuator/health
            port: 8080          
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
      volumes:
      - name: test-mount
        persistentVolumeClaim:
          claimName: test-mount-claim
