kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: test-service-gateway
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: {{ .Values.istio_gateway_port }}
    protocol: HTTP
