kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Release.Namespace }}-test-mount
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: {{ .Values.persistent_volume_path }}
  persistentVolumeReclaimPolicy: Retain
