kind: PersistentVolume
apiVersion: v1
metadata:
  name: test-mount
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/run/desktop/mnt/host/c/Projekte/docker/repository/docker-test/de.tecsi.docker.test/kubernetes/test-mount"
  persistentVolumeReclaimPolicy: Retain
