kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-mount-claim
spec:
  storageClassName: manual
  volumeName: {{ .Release.Namespace }}-test-mount
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
